services:
    php:
        build:
            context: .
        volumes:
            - ./:/var/www
        networks:
            - app
        expose:
            - 9000
    nginx:
        image: nginx:alpine
        container_name: app-nginx
        networks:
            - app
        depends_on:
            - php
        ports:
            - "${NGINX_PORT-8090}:8090"
            - "${NGINX_HTTP_PORT-443}:443"
        volumes:
            - ./:/var/www
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    db:
        platform: linux/x86_64
        image: mysql:5.6.47
        container_name: app-db
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app
        ports:
            - "3306:3306"
        volumes:
            - ./etc/infrastructure/mysql/my.cnf:/etc/mysql/my.cnf
            - ./etc/database/base.sql:/docker-entrypoint-initdb.d/base.sql

networks:
    app:
        driver: bridge
