name: Symfony CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        name: Build & Test
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: app
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3

        steps:
            - uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring, intl, pdo_mysql
                  coverage: none

            - name: Validate composer.json and composer.lock
              run: composer validate --strict

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run SA
              run: vendor/bin/phpstan analyse src

            - name: Create .env.test
              run: cp .env .env.test

            - name: Wait for MySQL
              run: |
                  until mysqladmin ping -h 127.0.0.1 --silent; do
                    sleep 1
                  done

            - name: Run Doctrine migrations
              run: php bin/console doctrine:migrations:migrate --no-interaction

            - name: Run Symfony tests
              run: php bin/phpunit
